#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

mkdir 0
cp initial/* 0
runApplication blockMesh
runApplication decomposePar -cellDist -force
#runParallel $application
runApplication $application
#runApplication reconstructParMesh -mergeTol 1e-6
runApplication reconstructPar
runApplication postProcess -funcs '(vorticity)'
touch cylinder.OpenFOAM

#------------------------------------------------------------------------------
